# Generated by Django 4.2.6 on 2023-10-10 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_breed_friendliness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="friendliness",
            field=models.PositiveIntegerField(
                default=1,
                help_text="It is help_text",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Friendly?",
            ),
        ),
    ]
